# serverless.yml
frameworkVersion: "=1.39.0"

service: randocat

package:
  exclude:
    - mypackage/**
    - node_modules/**
    - venv/**
    
provider:
  name: aws
  runtime: python3.6
  tracing:
    lambda: true
  vpc:
    securityGroupIds:
      - sg-058272a6cf48e74b4
    subnetIds:
      - subnet-045afd8c823675165
      - subnet-036e98e254d9d82dd

functions:
  hello:
    handler: handler.hello
  dbversion:
    handler: handler.dbversion
    
plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
 
# # you can add statements to the Lambda function's IAM Role here
# #  iamRoleStatements:
# #    - Effect: "Allow"
# #      Action:
# #        - "s3:ListBucket"
# #      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
# #    - Effect: "Allow"
# #      Action:
# #        - "s3:PutObject"
# #      Resource:
# #        Fn::Join:
# #          - ""
# #          - - "arn:aws:s3:::"
# #            - "Ref" : "ServerlessDeploymentBucket"
# #            - "/*"

# # you can define service wide environment variables here
# #  environment:
# #    variable1: value1
